2018-12-14T01:20:34.805Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T01:20:34.839Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T01:57:18.096Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T01:57:18.123Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T02:42:37.356Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T02:42:37.393Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T03:19:49.300Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T03:19:49.333Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T04:05:55.700Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T04:05:55.735Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T04:59:03.451Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T04:59:03.501Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T05:44:30.105Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T05:44:30.145Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T06:29:53.152Z ERROR   :HLFConnectionManager     :fabric-client()           [ChannelEventHub.js]: _connect - timed out after:300000 {}$
2018-12-14T06:29:53.185Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-12-14T06:49:05.728Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:49:05.731Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T06:49:53.559Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:49:53.560Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T06:50:05.073Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:50:05.073Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T06:50:49.478Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:50:49.479Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T06:51:14.320Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:51:14.320Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T06:53:31.316Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T06:53:31.316Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T07:16:36.025Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: attempt to get property isSlaughtered on an InvalidRelationship is not allowed. InvalidRelationship created due to Object with ID 'Cow_1' in collection with ID 'Asset:ch.cowchain.Cow' does not exist
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T07:16:36.026Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: attempt to get property isSlaughtered on an InvalidRelationship is not allowed. InvalidRelationship created due to Object with ID 'Cow_1' in collection with ID 'Asset:ch.cowchain.Cow' does not exist","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: attempt to get property isSlaughtered on an InvalidRelationship is not allowed. InvalidRelationship created due to Object with ID 'Cow_1' in collection with ID 'Asset:ch.cowchain.Cow' does not exist\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T07:16:49.385Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T07:16:49.386Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T07:17:29.077Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T07:17:29.078Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T18:30:34.202Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T18:30:34.203Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T18:32:00.767Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T18:32:00.768Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be registered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T18:35:25.868Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T18:35:25.868Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T18:59:00.726Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T18:59:00.727Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:03:14.021Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:03:14.021Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: TypeError: Cannot read property 'farmerName' of undefined\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:12:08.672Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#mtn3v8kxm15448147286386o3x4p80q class ch.cowchain.Cow has value Fri Dec 14 2018 19:12:08 GMT+0000 (UTC) expected a Relationship.
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:12:08.677Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#mtn3v8kxm15448147286386o3x4p80q class ch.cowchain.Cow has value Fri Dec 14 2018 19:12:08 GMT+0000 (UTC) expected a Relationship.","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#mtn3v8kxm15448147286386o3x4p80q class ch.cowchain.Cow has value Fri Dec 14 2018 19:12:08 GMT+0000 (UTC) expected a Relationship.\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:20:11.150Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#omnf0ia4w1544815211120k1u1ajrst class ch.cowchain.Cow has value Fri Dec 14 2018 19:20:11 GMT+0000 (UTC) expected a Relationship.
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:20:11.153Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#omnf0ia4w1544815211120k1u1ajrst class ch.cowchain.Cow has value Fri Dec 14 2018 19:20:11 GMT+0000 (UTC) expected a Relationship.","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: ValidationException: Model violation in instance ch.cowchain.Meat#omnf0ia4w1544815211120k1u1ajrst class ch.cowchain.Cow has value Fri Dec 14 2018 19:20:11 GMT+0000 (UTC) expected a Relationship.\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:37:15.238Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:37:15.238Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:42:41.910Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:42:41.912Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T19:57:29.994Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T19:57:29.996Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Cow must be slaughtered\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T22:32:24.838Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:24.840Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T22:32:35.721Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'ch.cowchain.Operator#Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:47.125Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:48.379Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:48.718Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:49.030Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:49.253Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:49.324Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:32:49.360Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:33:26.179Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-14T22:33:26.181Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-14T22:44:59.233Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Cow_2' in collection with ID 'Asset:ch.cowchain.Cow' does not exist
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-15T12:21:15.214Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-12-15T12:21:15.239Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' as the object already exists\n    at HLFConnection.invokeChainCode (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-12-15T12:21:56.160Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID 'Operator_1' in collection with ID 'Participant:ch.cowchain.Operator' does not exist; [cause=Unexpected properties for type ch.cowchain.Operator: OperatorName]
    at new createStatusError (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
